---
title: "ergo: interface entre R et Go"
author: "Romain François"
output: pdf_document
---

purrple.cat

Cowork'in 

4 rue Auguste Comte

34000 Montpellier

```romain@purrple.cat```

Mots clefs : Programmation, Performance, Concurrence, Parallelisme. 

R nous fournit un langage solide et flexible pour la pratique de la Data Science. 
Les projets comme reticulate [1] et Rcpp [2] ont établi qu'il peut être avantageux 
de coupler R avec un autre langage de programmation. Il est parfois question de 
performance, d'expressivité algorithmique ou simplement d'accès à des 
librairies existantes dans ces langages tiers. 

Go [3]  est un langage de programmation open source qui facilite
la création de logiciels simples, efficaces et robustes. Go est un langage simple et 
élégant, sa librairie standard est extremement riche. Go intègre nativement 
la programmation en concurrence permettant par exemple l'éxécution de code 
en parallèle. Le générateur de site hugo et la plate forme de conteneurisation docker
sont des exemples de logiciels populaires et puissants implémentés en Go. 

ergo est le mariage heureux entre R et Go, permettant l'invocation de code 
Go depuis un package R. ergo est en quelques sort un Rcpp pour Go, même si 
l'implémentation est radicalement différente. Nous passerons en revue les choix 
techniques mis en oeuvre pour le developpement du package ergo, quelques cas
d'utilisation de Go dans un package R via ergo. 

## Références
[1] JJ Allaire, Kevin Ushey and Yuan Tang (2018). reticulate: Interface to 'Python'. R package version 1.6.

[2] Dirk Eddelbuettel and Romain Francois (2011). Rcpp: Seamless R and C++ Integration. Journal of Statistical Software, 40(8),
  1-18. URL http://www.jstatsoft.org/v40/i08/
  
[3] The Go Programming Language (https://golang.org). 
